name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  
  deploy:
    runs-on: ubuntu-latest  

    steps:   
      - name: Checkoutcode  
        uses: actions/checkout@v1

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:  
          node-version: "20"  
      # Run npm install and build on our code
      - name: Install dependencies  
        run: npm install  
      - name: Build
        run: npm run build

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}  
          NETLIFY_SITE_ID:  ${{ secrets.SITE_ID }} 
        with:  
          args: deploy